import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from 'next/font/google'
 
const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <script
        async
        src="node_modules/@material-tailwind/html@latest/scripts/ripple.js"
      ></script>

      <script
        async
        src="https://unpkg.com/@material-tailwind/html@latest/scripts/ripple.js"
      ></script>

      <body className={roboto.className}>{children}</body>
    </html>
  );
}
